server/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('webchat.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('webchat.portal.urls', namespace='portal')),
    url(r'^', include('webchat.payments.urls', namespace='payments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

server/webchat/payments/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^card/$', view=views.ChangeCardView.as_view(), name='update_card'),
    url(regex=r'^make-payment/$', view=views.make_payment, name='make_payment'),
    url(regex=r'^make-payment-api/$', view=views.make_payment_api, name='make_payment_api'),
    url(regex=r'^make-quick-payment/$', view=views.AddCardAndPayView.as_view(), name='make_quick_payment'),

    url(regex=r'^coupon/$', view=views.check_coupon_api, name='check_coupon'),
]

server/webchat/portal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^$', view=views.portal, name='home'),
    url(regex=r'^feedback/$', view=views.feedback, name='feedback'),
    url(regex=r'^rooms/$', view=views.rooms, name='rooms'),
    url(regex=r'^statistics/$', view=views.statistics, name='statistics'),
    url(regex=r'^widgets/$', view=views.widgets, name='widgets'),

    url(regex=r'^disable-widget-tip/$', view=views.disable_widget_tip, name='disable_widget_tip'),
]

server/webchat/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

server/webchat/payments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.forms.utils import ErrorList
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from .models import UserPayment
from .models import PlanPrice
from .models import Coupon
from webchat.portal.models import Widget
from webchat.users.models import TRIAL_PERIOD
from .forms import CreditCardForm
from webchat.portal.views import generate_token
from webchat.mailers.payment_confirm_notify import PaymentConfirmNotifyMailer

stripe.api_key = settings.STRIPE_API_KEY


def get_price(plan_name):
    return int(PlanPrice.objects.get(slug=plan_name).price)


class ChangeCardView(FormView):
    template_name = 'payments/add_card.html'
    success_url = '/make-payment/'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        return super(ChangeCardView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(ChangeCardView, self).get_context_data(**kwargs)
        context['user'] = user
        context['payment_active'] = user.payment_active
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ChangeCardView, self).dispatch(*args, **kwargs)


@login_required
def make_payment(request):
    """We can use celery and call this function as a delayed task."""
    user = request.user
    data = dict()
    data['user'] = user
    now = timezone.now()
    standard_price = get_price('standard')

    data['standard_price'] = standard_price
    if Coupon.objects.filter(activated_by=user).exists():
        data['has_coupon'] = True
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
            data['standard_price'] = standard_price - discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > now:
                discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
                data['standard_price'] = standard_price - discount

    if user.paid_at:
        paid_period_expires_at = user.paid_at + datetime.timedelta(days=TRIAL_PERIOD)
        data['paid_period_expires_at'] = paid_period_expires_at
        if paid_period_expires_at < now:
            data['status'] = 200
        else:
            data['status'] = "You still have an existing active plan"
    else:
        if user.payment_active:
            data['status'] = 200
        else:
            data['status'] = 403
            data['invalid_card'] = True

    return render(request, 'payments/make_payment.html', data)


def make_payment_api(request):
    """ todo: move to DRF """
    user = request.user
    amount = get_price('standard')

    if Coupon.objects.filter(activated_by=user).exists():
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = amount * Coupon.objects.get(activated_by=user).discount / 100
            amount -= discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount

    if request.method == 'POST':
        user = request.user

        try:
            widget = Widget.objects.get(owner=request.user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=request.user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=request.user)[0]
        try:
            payment = UserPayment.objects.create(
                user=request.user,
                widget=widget,
                amount=amount,
                description="Charge for monthly subscription {}".format(request.user.email)
            )
            charge = stripe.Charge.create(
                amount=int(amount * 100),
                currency="usd",
                customer=user.stripe_id,
                description="Charge for monthly subscription {}".format(request.user.email),
            )
            payment.trx_id = charge.id
            payment.status = '2'
            payment.history = charge
            payment.save()

            user.plan = '1'
            user.payment_active = True
            user.is_trial = False
            user.paid_at = timezone.now()
            user.save()

            domain = Site.objects.get_current().domain
            url = "https://{}/users/{}/".format(domain, request.user.username)

            context = {
                'username': request.user.username,
                'email': request.user.email,
                'cost': int(payment.amount),
                'url': url,
                'transaction_id': payment.trx_id
            }
            PaymentConfirmNotifyMailer(request).send(context)

            return HttpResponse(json.dumps({"status": True}), content_type="application/json")
        except Exception as e:
            return HttpResponse(
                json.dumps({"status": False, "msg": str(e)}),
                content_type="application/json"
            )


def check_coupon_api(request):
    """ todo: move to DRF """
    if request.method == 'POST':
        coupon_number = request.POST.get('coupon_number')
        if coupon_number:
            try:
                coupon = Coupon.objects.get(number=coupon_number, expired=False)
                coupon.activated_by = request.user
                coupon.activated_at = timezone.now()
                coupon.expired = True
                coupon.save()
                return HttpResponse(json.dumps({'success': True}), content_type="application/json")
            except Coupon.DoesNotExist:
                return HttpResponse(json.dumps({'success': False}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponseForbidden()


class AddCardAndPayView(FormView):
    template_name = 'payments/add_and_pay.html'
    success_url = '/make-payment/?p=quick'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        amount = get_price('standard')

        if Coupon.objects.filter(activated_by=user).exists():
            coupon = Coupon.objects.get(activated_by=user)
            if not coupon.duration:
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount
            else:
                if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                    discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                    amount -= discount

        try:
            widget = Widget.objects.get(owner=user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=user)[0]
        try:

server/webchat/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from webchat.payments.models import UserPayment
from webchat.portal.models import Message
from webchat.portal.models import Room
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def dispatch(self, request, *args, **kwargs):
        self.username = self.kwargs['username']
        if self.username != request.user.username and not request.user.is_superuser:
            raise PermissionDenied  # HTTP 403
        return super(UserDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['messages_count'] = Message.objects.sent_count(self.request.user)
        context['rooms_count'] = Room.objects.as_member(self.request.user).count()
        context['payments'] = UserPayment.objects.filter(
            user=self.request.user,
            status='2'
        ).order_by('-created_at')
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, TemplateView):
    template_name = "users/user_list.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied  # HTTP 403
        return super(UserListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['user_list'] = User.objects.all()
        return context

server/webchat/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

server/webchat/templates/base.html
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="chat portal">
  <meta name="author" content="">
  <title>{% block meta_title %}{% endblock meta_title %} | Apartment Ocean</title>
  {% load staticfiles %}
  <link href='//fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

   <!-- Favicons, Touch Icons -->
  <link rel="apple-touch-icon" sizes="57x57" href='{% static "assets/images/apple-icon-57x57.png" %}'>
  <link rel="apple-touch-icon" sizes="60x60" href='{% static "assets/images/apple-icon-60x60.png" %}'>
  <link rel="apple-touch-icon" sizes="72x72" href='{% static "assets/images/apple-icon-72x72.png" %}'>
  <link rel="apple-touch-icon" sizes="76x76" href='{% static "assets/images/apple-icon-76x76.png" %}'>
  <link rel="apple-touch-icon" sizes="114x114" href='{% static "assets/images/apple-icon-114x114.png" %}'>
  <link rel="apple-touch-icon" sizes="120x120" href='{% static "assets/images/apple-icon-120x120.png" %}'>
  <link rel="apple-touch-icon" sizes="144x144" href='{% static "assets/images/apple-icon-144x144.png" %}'>
  <link rel="apple-touch-icon" sizes="152x152" href='{% static "assets/images/apple-icon-152x152.png" %}'>
  <link rel="apple-touch-icon" sizes="180x180" href='{% static "assets/images/apple-icon-180x180.png" %}'>
  <link rel="icon" type="image/png" href='{% static "assets/images/favicon-96x96.png" %}' sizes="96x96">
  <link rel="icon" type="image/png" href='{% static "assets/images/favicon-32x32.png" %}' sizes="32x32">
  <link rel="icon" type="image/png" href='{% static "assets/images/favicon-16x16.png" %}' sizes="16x16">
  <link rel="manifest" href='{% static "assets/images/manifest.json" %}'>
  <link rel="manifest" href='{% static "assets/images/browserconfig.xml" %}'>
  <meta name="theme-color" content="#ffffff">

  <!-- Stylesheets -->
  <link rel="stylesheet" href='{% static "global/css/bootstrap.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/css/bootstrap-extend.min.css" %}'>
  <link rel="stylesheet" href='{% static "assets/css/site.css" %}'>
  <!-- Plugins -->
  <link rel="stylesheet" href='{% static "global/vendor/animsition/animsition.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/asscrollable/asScrollable.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/switchery/switchery.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/intro-js/introjs.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/slidepanel/slidePanel.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/jquery-mmenu/jquery-mmenu.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/flag-icon-css/flag-icon.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/vendor/toastr/toastr.min.css" %}'>
  {% block main_style %}{% endblock main_style %}
  <!-- Fonts -->
  <link rel="stylesheet" href='{% static "global/fonts/web-icons/web-icons.min.css" %}'>
  <link rel="stylesheet" href='{% static "global/fonts/brand-icons/brand-icons.min.css" %}'>
  <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>
  <!--[if lt IE 9]>
    <script src='{% static "global/vendor/html5shiv/html5shiv.min.js" %}'></script>
    <![endif]-->
  <!--[if lt IE 10]>
    <script src='{% static "global/vendor/media-match/media.match.min.js" %}'></script>
    <script src='{% static "global/vendor/respond/respond.min.js" %}'></script>
    <![endif]-->
  <!-- Scripts -->
  <script src='{% static "global/vendor/modernizr/modernizr.min.js" %}'></script>
  <script src='{% static "global/vendor/breakpoints/breakpoints.min.js" %}'></script>
  <script>
  Breakpoints();
  </script>
</head>

<body class="{% block body_class %}{% endblock body_class %}">
  <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

  <!-- Page -->
  {% block content %}{% endblock content %}
  <!-- End Page -->
  <!-- Core  -->
  <script src='{% static "global/vendor/jquery/jquery.min.js" %}'></script>
  <script src='{% static "global/vendor/bootstrap/bootstrap.min.js" %}'></script>
  <script src='{% static "global/vendor/animsition/animsition.min.js" %}'></script>
  <script src='{% static "global/vendor/asscroll/jquery-asScroll.min.js" %}'></script>
  <script src='{% static "global/vendor/mousewheel/jquery.mousewheel.min.js" %}'></script>
  <script src='{% static "global/vendor/asscrollable/jquery.asScrollable.all.min.js" %}'></script>
  <script src='{% static "global/vendor/ashoverscroll/jquery-asHoverScroll.min.js" %}'></script>
  <!-- Plugins -->
  <script src='{% static "global/vendor/jquery-mmenu/jquery.mmenu.min.all.js" %}'></script>
  <script src='{% static "global/vendor/switchery/switchery.min.js" %}'></script>
  <script src='{% static "global/vendor/intro-js/intro.min.js" %}'></script>
  <script src='{% static "global/vendor/screenfull/screenfull.min.js" %}'></script>
  <script src='{% static "global/vendor/slidepanel/jquery-slidePanel.min.js" %}'></script>
  <script src='{% static "global/vendor/jquery-placeholder/jquery.placeholder.min.js" %}'></script>
  <script src='{% static "global/vendor/autosize/autosize.min.js" %}'></script>
  <script src='{% static "global/vendor/jdenticon/jdenticon-1.3.2.min.js" %}'></script>
  <script src='{% static "global/vendor/bootbox/bootbox.min.js" %}'></script>
  <script src='{% static "global/vendor/toastr/toastr.min.js" %}'></script>
  <!-- Scripts -->
  <script src='{% static "global/js/core.js" %}'></script>
  <script src='{% static "assets/js/site.js" %}'></script>
  <script src='{% static "assets/js/csrf.js" %}'></script>
  <script src='{% static "assets/js/sections/menu.js" %}'></script>
  <script src='{% static "assets/js/sections/menubar.js" %}'></script>
  <script src='{% static "assets/js/sections/gridmenu.js" %}'></script>
  <script src='{% static "global/js/configs/config-colors.js" %}'></script>
  <script src='{% static "global/js/components/asscrollable.js" %}'></script>
  <script src='{% static "global/js/components/animsition.js" %}'></script>
  <script src='{% static "global/js/components/slidepanel.js" %}'></script>
  <script src='{% static "global/js/components/switchery.js" %}'></script>
  <script src='{% static "global/js/components/jquery-placeholder.js" %}'></script>
  <script src='{% static "global/js/components/bootbox.js" %}'></script>
  {% block main_scripts %}{% endblock main_scripts %}
  <script>
  (function(document, window, $) {
    'use strict';
    var Site = window.Site;
    $(document).ready(function() {
      Site.run();
    });
  })(document, window, jQuery);
  </script>

  <script>

  {% if request.user.is_authenticated %}
    // init toastr notifications
    toastr.options = {
      "closeButton": true,
      "positionClass": "toast-top-center",
      "timeOut": "0",
      "extendedTimeOut": "0"
    }

    {% if not request.user.default_card or not request.user.payment_active %}
    toastr.options.onclick = function() {
      window.location = "{% url 'payments:update_card' %}";
    }
    toastr.error('Please update your payment information.');
    {% endif %}

    {% if request.user.is_trial %}
    toastr.options.onclick = function() {
      window.location = "{% url 'payments:make_payment' %}";
    }
    toastr.warning('You are in free trial period. You have {{ request.user.days_left }} days. Please change your plan.');
    {% endif %}

  {% endif %}

    $.urlParam = function(name){
        var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
        if (results==null){
           return null;
        }
        else{
           return results[1] || 0;
        }
    };
    var message = $.urlParam('message_sent');
    var dj_redirect = $.urlParam('next');
    var payment = $.urlParam('p');

    if (message == "success" || dj_redirect == "/%3Fmessage_sent%3Dsuccess" ) {
      toastr.success('Thank you for contacting us, someone will be in touch with you soon!');
    }
    if (payment == 'quick') {
      toastr.success('Thank you for your subscription!');
    }
  </script>

  <!-- Heap Analytics Start -->
  <script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
    heap.load("428749649");
  </script>
  <!-- Heap Analytics End -->
</body>

</html>

server/webchat/templates/base_footer.html
<footer class="site-footer">
  <div class="site-footer-legal">©<a href="https://www.apartmentocean.com/">Apartment Ocean</a>, 2016</div>
  <div class="site-footer-right">
    Crafted with <i class="red-600 wb wb-heart"></i> by <a href="https://www.apartmentocean.com/">ClikHome, Inc.</a>
  </div>
</footer>

server/webchat/templates/base_menubar.html
<div class="site-menubar">
  <ul class="site-menu">
    <li class="site-menu-item">
      <a class="animsition-link" href="{% url 'portal:home' %}">
        <i class="site-menu-icon wb-home" aria-hidden="true"></i>
        <span class="site-menu-title">Home</span>
      </a>
    </li>
    <li class="site-menu-item has-sub">
      <a href="javascript:void(0)">
        <i class="site-menu-icon wb-user-circle" aria-hidden="true"></i>
        <span class="site-menu-title">My Account</span>
        <span class="site-menu-arrow"></span>
      </a>
      <ul class="site-menu-sub">
        <li class="site-menu-item">
          <a class="animsition-link" href="{% url 'users:detail' request.user.username %}">
            <span class="site-menu-title">Profile</span>
          </a>
        </li>
      </ul>
    </li>
    {% if request.user.is_superuser %}
    <li class="site-menu-item">
      <a class="animsition-link" href="{% url 'admin:index' %}">
        <i class="site-menu-icon wb-wrench" aria-hidden="true"></i>
        <span class="site-menu-title">Admin Panel</span>
      </a>
    </li>
    <li class="site-menu-item">
      <a class="animsition-link" href="{% url 'users:list' %}">
        <i class="site-menu-icon wb-users" aria-hidden="true"></i>
        <span class="site-menu-title">Users</span>
      </a>
    </li>
    {% endif %}
    <li class="site-menu-item">
      <a class="animsition-link" href="{% url 'portal:statistics' %}">
        <i class="site-menu-icon wb-stats-bars" aria-hidden="true"></i>
        <span class="site-menu-title">Statistics</span>
      </a>
    </li>
    <li class="site-menu-item">
      <a class="animsition-link" href="{% url 'portal:widgets' %}">
        <i class="site-menu-icon wb-share" aria-hidden="true"></i>
        <span class="site-menu-title">Widget Install</span>
      </a>
    </li>
    <li class="site-menu-item">
      <a class="animsition-link" href="{% url 'payments:make_payment' %}">
        <i class="site-menu-icon wb-payment" aria-hidden="true"></i>
        <span class="site-menu-title">Pricing Plan</span>
      </a>
    </li>
  </ul>
</div>

server/webchat/templates/main_footer.html
<div class="footer clearfix">
  <div class="social_buttons">
    <a href="#" class="link_facebook">
      <img src="/static/assets/images/facebook.png" />
    </a>
    <a href="#" class="link_twitter">
      <img src="/static/assets/images/twitter.png" />
    </a>
    <a href="#" class="link_pinterest">
      <img src="/static/assets/images/pinterest.png" />
    </a>
  </div>
  <ul class="footer_menus">
    <li>
      <a href="/">Home</a>
    </li>
    <li class="chat_disabled"><span>|</span></li>
    <li>
      <a href="/agents">For Agents</a>
    </li>
    <li class="chat_disabled"><span>|</span></li>
    <li>
      <a href="/renters">For Renters</a>
    </li>
    <li class="chat_disabled"><span>|</span></li>
    <li>
      <a href="/terms">Terms &amp; Privacy</a>
    </li>
    <li class="chat_disabled"><span>|</span></li>
    <li>
      <a href="http://help.apartmentocean.com/">Support</a>
    </li>
  </ul>
  <div class="footer_policy">
    © 2016 ClikHome, Inc. All Rights Reserved.
  </div>
</div>