server/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('webchat.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('webchat.portal.urls', namespace='portal')),
    url(r'^', include('webchat.payments.urls', namespace='payments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

server/webchat/payments/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^card/$', view=views.ChangeCardView.as_view(), name='update_card'),
    url(regex=r'^make-payment/$', view=views.make_payment, name='make_payment'),
    url(regex=r'^make-payment-api/$', view=views.make_payment_api, name='make_payment_api'),
    url(regex=r'^make-quick-payment/$', view=views.AddCardAndPayView.as_view(), name='make_quick_payment'),

    url(regex=r'^coupon/$', view=views.check_coupon_api, name='check_coupon'),
]

server/webchat/portal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^$', view=views.portal, name='home'),
    url(regex=r'^feedback/$', view=views.feedback, name='feedback'),
    url(regex=r'^rooms/$', view=views.rooms, name='rooms'),
    url(regex=r'^statistics/$', view=views.statistics, name='statistics'),
    url(regex=r'^widgets/$', view=views.widgets, name='widgets'),

    url(regex=r'^disable-widget-tip/$', view=views.disable_widget_tip, name='disable_widget_tip'),
]

server/webchat/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

server/webchat/payments/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from calendar import monthrange
from datetime import date

from django import forms


class CreditCardField(forms.IntegerField):
    def clean(self, value):
        """Check if given CC number is valid and one of the card types we accept."""
        value = value.replace(' ', '')
        if value and (len(value) < 13 or len(value) > 16):
            raise forms.ValidationError("Please enter in a valid credit card number.")
        return super(CreditCardField, self).clean(value)


class CCExpWidget(forms.MultiWidget):
    """Widget containing two select boxes for selecting the month and year."""

    def decompress(self, value):
        return [value.month, value.year] if value else [None, None]

    def format_output(self, rendered_widgets):
        html = u' / '.join(rendered_widgets)
        return u'<span style="white-space: nowrap;">%s</span>' % html


class CCExpField(forms.MultiValueField):
    EXP_MONTH = [(x, x) for x in range(1, 13)]
    EXP_YEAR = [(x, x) for x in range(date.today().year, date.today().year + 15)]
    default_error_messages = {
        'invalid_month': u'Enter a valid month.',
        'invalid_year': u'Enter a valid year.',
    }

    def __init__(self, *args, **kwargs):
        errors = self.default_error_messages.copy()
        if 'error_messages' in kwargs:
            errors.update(kwargs['error_messages'])
        fields = (
            forms.ChoiceField(choices=self.EXP_MONTH,
                              error_messages={'invalid': errors['invalid_month']}),
            forms.ChoiceField(choices=self.EXP_YEAR,
                              error_messages={'invalid': errors['invalid_year']}),
        )
        super(CCExpField, self).__init__(fields, *args, **kwargs)
        self.widget = CCExpWidget(widgets=[fields[0].widget, fields[1].widget])

    def clean(self, value):
        exp = super(CCExpField, self).clean(value)
        if date.today() > exp:
            raise forms.ValidationError("The expiration date you entered is in the past.")

        return exp

    def compress(self, data_list):
        if data_list:
            if data_list[1] in forms.fields.EMPTY_VALUES:
                error = self.error_messages['invalid_year']
                raise forms.ValidationError(error)
            if data_list[0] in forms.fields.EMPTY_VALUES:
                error = self.error_messages['invalid_month']
                raise forms.ValidationError(error)
            year = int(data_list[1])
            month = int(data_list[0])
            # find last day of the month
            day = monthrange(year, month)[1]
            return date(year, month, day)
        return None


class CreditCardForm(forms.Form):
    name = forms.CharField(
        label="Full Name",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    number = CreditCardField(
        required=True,
        label="Card Number",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    expiration = CCExpField(
        required=True,
        label="Expiration"
    )
    cvc = forms.IntegerField(
        required=True,
        label="CVC Number",
        max_value=9999,
        widget=forms.TextInput(attrs={'size': '4', 'class': 'form-control'})
    )

    def clean(self):
        cleaned = super(CreditCardForm, self).clean()

        return cleaned

server/webchat/payments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.forms.utils import ErrorList
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from .models import UserPayment
from .models import PlanPrice
from .models import Coupon
from webchat.portal.models import Widget
from webchat.users.models import TRIAL_PERIOD
from .forms import CreditCardForm
from webchat.portal.views import generate_token
from webchat.mailers.payment_confirm_notify import PaymentConfirmNotifyMailer

stripe.api_key = settings.STRIPE_API_KEY


def get_price(plan_name):
    return int(PlanPrice.objects.get(slug=plan_name).price)


class ChangeCardView(FormView):
    template_name = 'payments/add_card.html'
    success_url = '/make-payment/'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        return super(ChangeCardView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(ChangeCardView, self).get_context_data(**kwargs)
        context['user'] = user
        context['payment_active'] = user.payment_active
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ChangeCardView, self).dispatch(*args, **kwargs)


@login_required
def make_payment(request):
    """We can use celery and call this function as a delayed task."""
    user = request.user
    data = dict()
    data['user'] = user
    now = timezone.now()
    standard_price = get_price('standard')

    data['standard_price'] = standard_price
    if Coupon.objects.filter(activated_by=user).exists():
        data['has_coupon'] = True
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
            data['standard_price'] = standard_price - discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > now:
                discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
                data['standard_price'] = standard_price - discount

    if user.paid_at:
        paid_period_expires_at = user.paid_at + datetime.timedelta(days=TRIAL_PERIOD)
        data['paid_period_expires_at'] = paid_period_expires_at
        if paid_period_expires_at < now:
            data['status'] = 200
        else:
            data['status'] = "You still have an existing active plan"
    else:
        if user.payment_active:
            data['status'] = 200
        else:
            data['status'] = 403
            data['invalid_card'] = True

    return render(request, 'payments/make_payment.html', data)


def make_payment_api(request):
    """ todo: move to DRF """
    user = request.user
    amount = get_price('standard')

    if Coupon.objects.filter(activated_by=user).exists():
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = amount * Coupon.objects.get(activated_by=user).discount / 100
            amount -= discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount

    if request.method == 'POST':
        user = request.user

        try:
            widget = Widget.objects.get(owner=request.user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=request.user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=request.user)[0]
        try:
            payment = UserPayment.objects.create(
                user=request.user,
                widget=widget,
                amount=amount,
                description="Charge for monthly subscription {}".format(request.user.email)
            )
            charge = stripe.Charge.create(
                amount=int(amount * 100),
                currency="usd",
                customer=user.stripe_id,
                description="Charge for monthly subscription {}".format(request.user.email),
            )
            payment.trx_id = charge.id
            payment.status = '2'
            payment.history = charge
            payment.save()

            user.plan = '1'
            user.payment_active = True
            user.is_trial = False
            user.paid_at = timezone.now()
            user.save()

            domain = Site.objects.get_current().domain
            url = "https://{}/users/{}/".format(domain, request.user.username)

            context = {
                'username': request.user.username,
                'email': request.user.email,
                'cost': int(payment.amount),
                'url': url,
                'transaction_id': payment.trx_id
            }
            PaymentConfirmNotifyMailer(request).send(context)

            return HttpResponse(json.dumps({"status": True}), content_type="application/json")
        except Exception as e:
            return HttpResponse(
                json.dumps({"status": False, "msg": str(e)}),
                content_type="application/json"
            )


def check_coupon_api(request):
    """ todo: move to DRF """
    if request.method == 'POST':
        coupon_number = request.POST.get('coupon_number')
        if coupon_number:
            try:
                coupon = Coupon.objects.get(number=coupon_number, expired=False)
                coupon.activated_by = request.user
                coupon.activated_at = timezone.now()
                coupon.expired = True
                coupon.save()
                return HttpResponse(json.dumps({'success': True}), content_type="application/json")
            except Coupon.DoesNotExist:
                return HttpResponse(json.dumps({'success': False}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponseForbidden()


class AddCardAndPayView(FormView):
    template_name = 'payments/add_and_pay.html'
    success_url = '/make-payment/?p=quick'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        amount = get_price('standard')

        if Coupon.objects.filter(activated_by=user).exists():
            coupon = Coupon.objects.get(activated_by=user)
            if not coupon.duration:
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount
            else:
                if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                    discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                    amount -= discount

        try:
            widget = Widget.objects.get(owner=user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=user)[0]
        try:

server/webchat/templates/payments/add_and_pay.html
{% extends "base.html" %}

{% block meta_title %}Activating Standard Plan {% endblock meta_title %}

{% load staticfiles %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/statistics.css" %}'>
{% endblock main_style %}

{% block body_class %}site-navbar-small app-message{% endblock body_class %}


{% block content %}

{% include "base_navbar.html" %}

{% include "base_menubar.html" %}

<!-- Page -->
<div class="page animsition">
  <div class="page-header">
    <h1 class="page-title">Your Payment Setting</h1>
  </div>
  <div class="page-content container-fluid">
    <div class="panel">
      <div class="panel" id="exampleWizardFormContainer">
        <div class="panel-heading">
          <h3 class="panel-title">You are almost done</h3>
            <h3></h3>
        </div>
        <div class="panel-body">
              <div class="pearls row">
                <div class="pearl current col-xs-4">
                  <div class="pearl-icon"><i class="icon wb-user" aria-hidden="true"></i></div>
                  <span class="pearl-title">Account Info</span>
                </div>
                <div class="pearl current col-xs-4">
                  <div class="pearl-icon"><i class="icon wb-payment" aria-hidden="true"></i></div>
                  <span class="pearl-title">Billing Info</span>
                </div>
                <div class="pearl col-xs-4">
                  <div class="pearl-icon"><i class="icon wb-check" aria-hidden="true"></i></div>
                  <span class="pearl-title">Confirmation</span>
                </div>
              </div>
          <div class="clearfix form-group">
            <div class="card-wrapper pull-left" id="cardContainer"></div>
          </div>
          <form class="wizard-content" data-plugin="card" data-target="#cardContainer" action="" method="post">
            {% csrf_token %}
            <div class="wizard-pane" id="exampleBillingOne" role="tabpanel">
              {% if user.card_last %}
              <div class="form-group">
                <label class="control-label" for="">Current Card</label>
                <input type="text" class="form-control" readonly disabled value="{{ user.card_type }}
                      XXXXXXXX{{ user.card_last|default:"" }}
                      Exp {{ user.card_expiry }}">
              </div>
              {% endif %}
              <div class="form-group">
                <label class="control-label" for="id_card_number">Card Number</label>
                <i style="color: red">{{ form.number.errors.as_text }}</i>
                <input type="text" class="form-control has-error" value="{{ form.number.value|default:"" }}" name="number">
              </div>
              <div class="form-group">
                <label class="control-label" for="id_fullname">Full Name</label>
                <i style="color: red">{{ form.name.errors.as_text }}</i>
                <input type="text" value="{{ form.name.value|default:"" }}" name="name" class="form-control">
              </div>
              <div class="form-group">
                <label for="">Card Expiry</label>
                {{ form.expiration }}
                <i style="color: red">{{ form.expiration.errors.as_text }}</i>
              </div>
              <div class="form-group">
                <label class="control-label" for="id_cvc">CVC</label>
                <i style="color: red">{{ form.cvc.errors.as_text }}</i>
                <input type="text" value="{{ form.cvc.value|default:"" }}" name="cvc" class="form-control">
              </div>
              <div class="text-right">
                <button type="submit" class="btn btn-animate btn-animate-side btn-primary">
                  <span><i class="icon wb-shopping-cart" style="left: -6px;" aria-hidden="true"></i> Save and Activate Plan</span>
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Page -->
<!-- Footer -->
{% include "base_footer.html" %}

{% endblock content %}

{% block main_scripts %}
<script src='{% static "assets/js/app.js" %}'></script>
<script src='{% static "global/vendor/clipboard/clipboard.min.js" %}'></script>
<script src='{% static "global/vendor/card/jquery.card.min.js" %}'></script>
<script src='{% static "global/js/components/card.js" %}'></script>
<!-- Instantiate clipboard -->
<script>
  var clipboard = new Clipboard('.btn');
</script>
{% endblock main_scripts %}

server/webchat/templates/payments/make_payment.html
{% extends "base.html" %}

{% block meta_title %}Make a payment{% endblock meta_title %}

{% load staticfiles %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/statistics.css" %}'>
<link rel="stylesheet" href='{% static "assets/css/payments.css" %}'>
{% endblock main_style %}

{% block body_class %}site-navbar-small app-message{% endblock body_class %}


{% block content %}

{% include "base_navbar.html" %}

{% include "base_menubar.html" %}

<!-- Page -->
<div class="page animsition">
  <div class="page-header">
    <h1 class="page-title">Pricing Plan</h1>
  </div>
  <div class="page-content container-fluid">
    <div class="panel" id="exampleWizardFormContainer">
      <div class="panel-heading">
        <h3 class="panel-title">Choose your plan</h3>
      </div>
      <div class="panel-body container-fluid">
        <!-- Example Pricing List -->
        <div class="example-wrap">
          <div class="example">
            <div class="row">
              <div class="col-sm-6 col-lg-4 col-lg-offset-2">
                <div class="pricing-list">
                  <div class="pricing-header">
                    <div class="pricing-title bg-blue-600">
                    {% if has_coupon %}
                      <div class="ribbon ribbon-clip ribbon-warning coupon">
                        <span class="ribbon-inner">discount</span>
                      </div>
                    {% endif %}
                        Standard</div>
                    <div class="pricing-price">
                      <span class="pricing-currency blue-600">$</span>
                      <span class="pricing-amount blue-600">{{ standard_price }}</span>
                      <span class="pricing-period">/ mo</span>
                    </div>
                  </div>
                  <ul class="pricing-features">
                    <li>
                      Easy To Install Chat Button</li>
                    <li>
                      Automatically receive requests from website visitors</li>
                    <li>
                      Generate customizable automated responses to customer’s questions</li>
                    <li>
                      Call joining so an agent can join the conversation at any time</li>
                    <li>
                      Our Proprietary Customer Conversation Management System</li>
                  </ul>
                  <div class="pricing-footer">

                    {% if status == 200 or status == 403 %}
                        <a {% if invalid_card %}href="{% url 'payments:make_quick_payment' %}"{% endif %} class="btn btn-primary btn-outline {% if not invalid_card %}submit_payment{% endif %}" id="join_button" role="button"><i class="icon wb-arrow-right font-size-16 margin-right-15" aria-hidden="true"></i>First Month Free! Join Now!</a>

                            {% if not has_coupon %}
                        <div class="panel-group" id="exampleAccordionDefault" aria-multiselectable="true" role="tablist">
                          <div class="panel">
                            <div class="panel-heading" id="exampleHeadingDefaultOne" role="tab">
                              <a class="panel-title" data-toggle="collapse" href="#exampleCollapseDefaultOne" data-parent="#exampleAccordionDefault" aria-expanded="true" aria-controls="exampleCollapseDefaultOne">
                                                Do you have a coupon?
                                            </a>
                            </div>
                            <div class="panel-collapse collapse" id="exampleCollapseDefaultOne" aria-labelledby="exampleHeadingDefaultOne" role="tabpanel">
                              <div class="panel-body">
                                <div class="form-group has-feedback" id="coupon_form">
                                  <div class="row">
                                    <small class="control-label red-600" id="error_message" style="display: none">
                                                            Sorry this code is invalid or expired :(
                                                        </small>
                                    <form action="{% url 'payments:check_coupon' %}" method="post">
                                      {% csrf_token %}
                                      <div>
                                        <input type="text" class="form-control" id="id_coupon_number" aria-describedby="inputErrorStatus" name="coupon_number" autocomplete="off">
                                        <span class="form-control-feedback" aria-hidden="true"></span>
                                        <span class="sr-only" id="inputErrorStatus">(error)</span>
                                        <button type="submit" onclick="return false" id="coupon_submit" class="btn btn-outline btn-default btn-xs">Use Coupon</button>
                                      </div>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {% endif %}

                    {% else %}
                    <a class="btn btn-primary btn-outline bg-blue-600" role="button"><i class="icon wb-check-circle font-size-16 margin-right-15" aria-hidden="true"></i>Your Current Plan</a>
                    {% endif %}
                    <div class="alert alert-alt alert-danger alert-dismissible"
                         role="alert" id="error_msg" style="display: none">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                      <p id="msg"></p>.
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-lg-4">
                <div class="pricing-list">
                  <div class="pricing-header">
                    <div class="pricing-title bg-green-600">Custom</div>
                  </div>
                  <ul class="pricing-features">
                    <li>Customized Chat Button</li>
                    <li>Automatically receive requests from website visitors</li>
                    <li>Generate customizable automated responses to customer’s questions</li>
                    <li>Call joining so an agent can join the conversation at any time</li>
                    <li>Our Proprietary Customer Conversation Management System</li>
                    <li></li>
                  </ul>
                  <span>And Also Receive These <strong>BONUS</strong> Features:</span>
                  <ul class="pricing-features">
                    <li></li>
                    <li>Automated Lead Creation</li>
                    <li>Customized Admin Portal</li>
                    <li>Easy management and distribution of leads</li>
                    <li>Customized questions Customized Artificial Intelligence responses</li>
                  </ul>
                  <div class="pricing-footer" style="padding: 18px 0;">
                    <a href="{% url 'portal:feedback' %}" class="btn btn-primary btn-outline" role="button"><i class="icon wb-arrow-right font-size-16 margin-right-15" aria-hidden="true"></i>Contact Us Today For A Free <br>Customized Plan For Your Business</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- End Example Pricing List -->
          <div style="display: none;">
              <form action="{% url 'payments:make_payment_api' %}" id="make_payment_api_form" method="post">
                  {% csrf_token %}

                  <button onclick="return false" type="submit" class="btn btn-animate btn-animate-side btn-primary submit_payment">
                      <span><i class="icon wb-shopping-cart" aria-hidden="true"></i> Activate Standard Plan</span>
                  </button>
              </form>
          </div>
      </div>
    </div>
  </div>
</div>
<!-- End Page -->

<!-- Footer -->
{% include "base_footer.html" %}

{% endblock content %}

{% block main_scripts %}
<script src='{% static "assets/js/app.js" %}'></script>
<script type="text/javascript">
  var frm = $('#make_payment_api_form');
  var btn = $('.submit_payment');
  var wait_msg = $('#wait_msg');
  var join_button = $('#join_button');

  btn.on('click', function() {
    btn.css('opacity', 0.8).prop('disabled', true);
    join_button.css('opacity', 0.8).prop('disabled', true);
    join_button.prop('disabled', true).addClass('bg-orange-600').text('Processing ...');
    wait_msg.fadeIn();

    $.ajax({
      type: frm.attr('method'),
      url: frm.attr('action'),
      data: frm.serialize(),
      success: function(data) {
        if (data.status) {
          wait_msg.fadeOut('fast');
          $('#success_msg').fadeIn();
          join_button.removeClass('bg-orange-600').addClass('bg-green-600').text('Success! Thank you!');
          setTimeout(location.reload.bind(location), 2000);
        } else {
          wait_msg.fadeOut('fast');
            join_button.removeClass('bg-orange-600').addClass('bg-red-600').text('Error during authorization');
          $('#error_msg').fadeIn();
          $('#msg').text(data.msg);
        }
      }
    });
  });

  var coupon_form = $('#coupon_form');
  var coupon_submit = $('#coupon_submit');
  coupon_submit.on('click', function () {
    $.ajax({
      type: 'POST',
      url: {% url 'payments:check_coupon' %},
      data: {'coupon_number': $('#id_coupon_number').val()},
      success: function(data) {
        if (data.success) {
            $('#error_message').fadeOut();
            coupon_form.removeClass('has-error');
            coupon_form.addClass('has-success');
            coupon_submit.removeClass('btn-default').addClass('btn-success');
            coupon_submit.text('Thanks! Your code is accepted.');
            setTimeout(location.reload.bind(location), 1000);
        } else {
            coupon_form.addClass('has-error');
            $('#error_message').fadeIn();
        }
      }
    });
  });
</script>
{% endblock main_scripts %}