server/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('webchat.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('webchat.portal.urls', namespace='portal')),
    url(r'^', include('webchat.payments.urls', namespace='payments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

server/webchat/payments/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^card/$', view=views.ChangeCardView.as_view(), name='update_card'),
    url(regex=r'^make-payment/$', view=views.make_payment, name='make_payment'),
    url(regex=r'^make-payment-api/$', view=views.make_payment_api, name='make_payment_api'),
    url(regex=r'^make-quick-payment/$', view=views.AddCardAndPayView.as_view(), name='make_quick_payment'),

    url(regex=r'^coupon/$', view=views.check_coupon_api, name='check_coupon'),
]

server/webchat/portal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^$', view=views.portal, name='home'),
    url(regex=r'^feedback/$', view=views.feedback, name='feedback'),
    url(regex=r'^rooms/$', view=views.rooms, name='rooms'),
    url(regex=r'^statistics/$', view=views.statistics, name='statistics'),
    url(regex=r'^widgets/$', view=views.widgets, name='widgets'),

    url(regex=r'^disable-widget-tip/$', view=views.disable_widget_tip, name='disable_widget_tip'),
]

server/webchat/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

server/webchat/payments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.forms.utils import ErrorList
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from .models import UserPayment
from .models import PlanPrice
from .models import Coupon
from webchat.portal.models import Widget
from webchat.users.models import TRIAL_PERIOD
from .forms import CreditCardForm
from webchat.portal.views import generate_token
from webchat.mailers.payment_confirm_notify import PaymentConfirmNotifyMailer

stripe.api_key = settings.STRIPE_API_KEY


def get_price(plan_name):
    return int(PlanPrice.objects.get(slug=plan_name).price)


class ChangeCardView(FormView):
    template_name = 'payments/add_card.html'
    success_url = '/make-payment/'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        return super(ChangeCardView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(ChangeCardView, self).get_context_data(**kwargs)
        context['user'] = user
        context['payment_active'] = user.payment_active
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ChangeCardView, self).dispatch(*args, **kwargs)


@login_required
def make_payment(request):
    """We can use celery and call this function as a delayed task."""
    user = request.user
    data = dict()
    data['user'] = user
    now = timezone.now()
    standard_price = get_price('standard')

    data['standard_price'] = standard_price
    if Coupon.objects.filter(activated_by=user).exists():
        data['has_coupon'] = True
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
            data['standard_price'] = standard_price - discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > now:
                discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
                data['standard_price'] = standard_price - discount

    if user.paid_at:
        paid_period_expires_at = user.paid_at + datetime.timedelta(days=TRIAL_PERIOD)
        data['paid_period_expires_at'] = paid_period_expires_at
        if paid_period_expires_at < now:
            data['status'] = 200
        else:
            data['status'] = "You still have an existing active plan"
    else:
        if user.payment_active:
            data['status'] = 200
        else:
            data['status'] = 403
            data['invalid_card'] = True

    return render(request, 'payments/make_payment.html', data)


def make_payment_api(request):
    """ todo: move to DRF """
    user = request.user
    amount = get_price('standard')

    if Coupon.objects.filter(activated_by=user).exists():
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = amount * Coupon.objects.get(activated_by=user).discount / 100
            amount -= discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount

    if request.method == 'POST':
        user = request.user

        try:
            widget = Widget.objects.get(owner=request.user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=request.user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=request.user)[0]
        try:
            payment = UserPayment.objects.create(
                user=request.user,
                widget=widget,
                amount=amount,
                description="Charge for monthly subscription {}".format(request.user.email)
            )
            charge = stripe.Charge.create(
                amount=int(amount * 100),
                currency="usd",
                customer=user.stripe_id,
                description="Charge for monthly subscription {}".format(request.user.email),
            )
            payment.trx_id = charge.id
            payment.status = '2'
            payment.history = charge
            payment.save()

            user.plan = '1'
            user.payment_active = True
            user.is_trial = False
            user.paid_at = timezone.now()
            user.save()

            domain = Site.objects.get_current().domain
            url = "https://{}/users/{}/".format(domain, request.user.username)

            context = {
                'username': request.user.username,
                'email': request.user.email,
                'cost': int(payment.amount),
                'url': url,
                'transaction_id': payment.trx_id
            }
            PaymentConfirmNotifyMailer(request).send(context)

            return HttpResponse(json.dumps({"status": True}), content_type="application/json")
        except Exception as e:
            return HttpResponse(
                json.dumps({"status": False, "msg": str(e)}),
                content_type="application/json"
            )


def check_coupon_api(request):
    """ todo: move to DRF """
    if request.method == 'POST':
        coupon_number = request.POST.get('coupon_number')
        if coupon_number:
            try:
                coupon = Coupon.objects.get(number=coupon_number, expired=False)
                coupon.activated_by = request.user
                coupon.activated_at = timezone.now()
                coupon.expired = True
                coupon.save()
                return HttpResponse(json.dumps({'success': True}), content_type="application/json")
            except Coupon.DoesNotExist:
                return HttpResponse(json.dumps({'success': False}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponseForbidden()


class AddCardAndPayView(FormView):
    template_name = 'payments/add_and_pay.html'
    success_url = '/make-payment/?p=quick'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        amount = get_price('standard')

        if Coupon.objects.filter(activated_by=user).exists():
            coupon = Coupon.objects.get(activated_by=user)
            if not coupon.duration:
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount
            else:
                if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                    discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                    amount -= discount

        try:
            widget = Widget.objects.get(owner=user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=user)[0]
        try:

server/webchat/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from webchat.payments.models import UserPayment
from webchat.portal.models import Message
from webchat.portal.models import Room
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def dispatch(self, request, *args, **kwargs):
        self.username = self.kwargs['username']
        if self.username != request.user.username and not request.user.is_superuser:
            raise PermissionDenied  # HTTP 403
        return super(UserDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['messages_count'] = Message.objects.sent_count(self.request.user)
        context['rooms_count'] = Room.objects.as_member(self.request.user).count()
        context['payments'] = UserPayment.objects.filter(
            user=self.request.user,
            status='2'
        ).order_by('-created_at')
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, TemplateView):
    template_name = "users/user_list.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied  # HTTP 403
        return super(UserListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['user_list'] = User.objects.all()
        return context

server/webchat/templates/portal/feedback.html
{% extends "base.html" %}

{% block meta_title %}Feedback{% endblock meta_title %}

{% load staticfiles %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/login.css" %}'>
{% endblock main_style %}

{% block body_class %}page-login layout-full{% endblock body_class %}

{% block content %}

<div class="container">
  <div class="page animsition vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">
    <div class="page-content vertical-align-middle">
      <div class="brand">
        <img class="brand-img" src='{% static "assets/images/logo.png" %}' alt="...">
        <h2 class="brand-text">Apartment Ocean</h2>
      </div>
      <p>Feel free to send us a message</p>
      <form method="post" role="form" action=".">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-error has-error">
          <p class="control-label">Please check these fields and try again:</p>
          <ul class="list-unstyled">
            {% for error in form.errors %}
              <li class="control-label">{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <div class="form-group">
          <label class="sr-only" for="inputName">First Name</label>
          <input type="text" class="form-control" id="inputFirstName" name="first_name" placeholder="Your First Name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="inputName">Last Name</label>
          <input type="text" class="form-control" id="inputLastName" name="last_name" placeholder="Last Name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="inputEmail">Email</label>
          <input type="email" class="form-control" id="inputEmail1" name="email1" placeholder="Email">
        </div>
        <div class="form-group">
          <label class="sr-only" for="inputEmail">Retype Email</label>
          <input type="email" class="form-control" id="inputEmail2" name="email2" placeholder="Please Retype Email">
          <i style="color: #f96868">{{ form.email2.errors.as_text }}</i>
        </div>
        <div class="form-group">
          <label class="sr-only" for="inputEmail">Message</label>
          <textarea class="maxlength-textarea form-control" data-plugin="maxlength" data-placement="bottom-right-inside" maxlength="500" rows="3" placeholder="Your message" name="body"></textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Send</button>
      </form>
    </div>
  </div>
  {% include "main_footer.html" %}
</div>

{% endblock content %}

server/webchat/templates/portal/home.html
{% extends "base.html" %}

{% block meta_title %}Chat Portal{% endblock meta_title %}

{% load staticfiles %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/portal.css" %}'>
{% endblock main_style %}

{% block body_class %}site-navbar-small app-message{% endblock body_class %}

{% block content %}

<input type="hidden" id="sessionkey" value='{{ request.session.session_key }}'>
<input type="hidden" id="username" value='{{ request.user.username }}'>
<input type="hidden" id="roomsUrl" value="{% url 'portal:rooms' %}">

{% include "base_navbar.html" %}

{% include "base_menubar.html" %}

<div class="page animsition">
  <!-- Message Sidebar -->
  <div class="page-aside">
    <div class="page-aside-switch">
      <i class="icon wb-chevron-left" aria-hidden="true"></i>
      <i class="icon wb-chevron-right" aria-hidden="true"></i>
    </div>
    <div class="page-aside-inner">
      <div class="app-message-list" data-plugin="pageAsideScroll">
        <div data-role="container">
          <div data-role="content">
            <ul class="list-group rooms">
            {% include "portal/rooms_chat.html" %}
            </ul>
          </div>
        </div>
      </div>
      <div class="new-room clearfix" style="display: none;">
        <button class="new-room-btn btn btn-floating btn-primary btn-sm" type="button"><i aria-hidden="true" class="icon wb-plus"></i></button>
      </div>
    </div>
  </div>
  <!-- End Message Sidebar -->
  <div class="page-main">
    <!-- Chat Box -->
    <div class="app-message-chats">
      <div class="chats">
        {% include "portal/message_chat.html" %}
      </div>
    </div>
    <!-- End Chat Box -->
    <!-- Message Input-->
    <form class="app-message-input">
      <div class="message-input">
        <textarea class="form-control" rows="1"></textarea>
      </div>
      <button class="message-input-btn btn btn-primary" type="button">SEND</button>
    </form>
    <!-- End Message Input-->
  </div>
</div>

<!-- Footer -->
{% include "base_footer.html" %}

{% endblock content %}

{% block main_scripts %}
<script src='{% static "global/vendor/reconnecting-websocket/reconnecting-websocket.min.js" %}'></script>
<script src='{% static "assets/js/app.js" %}'></script>
<script src='{% static "assets/js/portal.js" %}'></script>
{% if not rooms and request.user.show_widget_tip %}
    <script>
        $('#openTutorialModal').click();

        $('#disable_widget_tip').on('click', function () {
          $.get({% url 'portal:disable_widget_tip' %}, function( data ) {});
        })
    </script>
{% endif %}
{% endblock main_scripts %}

server/webchat/templates/portal/message_chat.html
{% load staticfiles %}
<p class="time">Last 10 messages</p>
{% for message in messages %}
<div class="chat{% if not message.is_support_sender %} chat-left{% endif %}">
  <div class="chat-avatar" {% ifchanged message.nickname %}{% else %}style="display: none;" {% endifchanged %}>
    <a class="avatar avatar-online" data-toggle="tooltip" href="#" data-placement="right" title="">
      {% if message.sender.user.avatar %}
      <img src='{{ message.sender.user.avatar.url }}' alt="{{ message.sender.get_full_name|default:message.sender.username }}">
      {% else %}
      <img src='{% static "global/portraits/default.jpg" %}' alt="No Avatar">
      {% endif %}
      <i></i>
    </a>
    <div class="message-info">
      <h5>{% if message.sender %}{{ message.sender }}{% else %}{{ message.nickname }}{% endif %}</h5>
    </div>
  </div>
  <div class="chat-body"
    {% ifchanged message.nickname %}
      {% if message.room.owner == request.user and message.sender == request.user %}
      {% else %}
        style="margin-top: 70px;"
      {% endif %}
    {% else %}
      style="margin: 0 60px;"
    {% endifchanged %}>
    <div class="chat-content {% ifchanged message.nickname %}{% else %}no-before{% endifchanged %}">
      <p>
        {{ message.body }}
      </p>
      <time datetime="{{ message.sent_at|date:'Y-m-d\TH:i' }}" class="message-time">{{ message.formatted_sent_at_time }}</time>
    </div>
  </div>
</div>
{% endfor %}

server/webchat/templates/portal/rooms_chat.html
{% load portal_tags %}
{% load humanize %}
{% if not rooms %}
<div class="no-items">You have no Chats</div>
  <button style="display: none" class="btn btn-primary" id="openTutorialModal" data-target="#exampleFillIn" data-toggle="modal"
  type="button">Generate</button>

  <div class="modal fade modal-fill-in" id="exampleFillIn" aria-hidden="false" aria-labelledby="exampleFillIn"
  role="dialog" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content" style="background: #fff;">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h5 class="modal-title example-title" id="exampleFillInModalTitle">To start using WebChat bot, you need to add
          the installation code to your website</h5>
        </div>
        <div class="modal-body">
            <div class="row">
              <div class="col-lg-12">
                <h5>Copy and paste this code snippet</h5>
                Place this code snippet on your website before the closing <code>&lt;&frasl;body&gt;</code> tag on pages you'd like it to appear.

              <textarea class="form-control text-break" id="snippet" rows="2" readonly>
                {% include "widgets/widget_snippet.html" %}
              </textarea>
              <div class="text-right margin-top-20">
                <button type="button" class="btn btn-outline btn-default btn-sm" data-clipboard-target="#snippet">Copy</button>
              </div>
              <h5>You can also customize your widget by setting custom <code>{username}</code> and verify your installation</h5>
              <a href="{% url 'portal:widgets' %}" class="btn btn-outline btn-default btn-sm">Customize</a>
              </div>
              </div>
        </div>
      </div>
            <a class="text-right small" data-dismiss="modal" href="" id="disable_widget_tip">I'll do it later...</a>

    </div>
  </div>
{% endif %}
{% for room in rooms %}
<li class="list-group-item{% if forloop.first %} active{% endif %}" data-label="{{ room.label }}" data-name="{{ room.name }}">
  <div class="media">
    <div class="media-left">
      <a class="avatar avatar-online" href="javascript:void(0)">
        <svg width="40" height="40" viewBox="0 0 40 40" data-jdenticon-hash="{{ room.label|md5 }}"></svg>
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">{{ room.name }}</h4>
      <span class="media-time">{{ room.created_at|naturaltime }}</span>
    </div>
    <div class="media-right">
      <span class="badge badge-default">{{ room.messages.count }}</span>
      <div class="item-actions">
        <span class="btn btn-pure btn-icon" data-tag="list-delete"><i class="icon wb-trash" aria-hidden="true"></i></span>
      </div>
    </div>
  </div>
</li>
{% endfor %}

server/webchat/templates/portal/statistics.html
{% extends "base.html" %}

{% block meta_title %}Statistics{% endblock meta_title %}

{% load staticfiles %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/statistics.css" %}'>
{% endblock main_style %}

{% block body_class %}site-navbar-small app-message{% endblock body_class %}

{% block content %}

{% include "base_navbar.html" %}

{% include "base_menubar.html" %}

  <!-- Page -->
  <div class="page animsition">
    <div class="page-header">
      <h1 class="page-title">Statistics</h1>
    </div>
    <div class="page-content container-fluid">
      <div class="row">
        <div class="clearfix visible-lg-block"></div>
        <div class="col-sm-4">
          <!-- Widget -->
          <div class="widget">
            <div class="widget-content padding-30 bg-blue-600">
              <div class="widget-watermark darker font-size-60 margin-15"><i class="icon wb-chat-group" aria-hidden="true"></i></div>
              <div class="counter counter-md counter-inverse text-left">
                <div class="counter-number-group">
                  <span class="counter-number">{{ total_rooms }}</span>
                  <span class="counter-number-related text-capitalize">Chats</span>
                </div>
                <div class="counter-label">We received in Chat Portal</div>
              </div>
            </div>
          </div>
          <!-- End Widget -->
        </div>
        <div class="col-sm-4">
          <!-- Widget -->
          <div class="widget">
            <div class="widget-content padding-30 bg-red-600">
              <div class="widget-watermark darker font-size-60 margin-15"><i class="icon wb-envelope" aria-hidden="true"></i></div>
              <div class="counter counter-md counter-inverse text-left">
                <div class="counter-number-group">
                  <span class="counter-number">{{ total_messages }}</span>
                  <span class="counter-number-related text-capitalize">Messages</span>
                </div>
                <div class="counter-label">We received in Chats</div>
              </div>
            </div>
          </div>
          <!-- End Widget -->
        </div>
        {% if request.user.is_superuser or request.user.is_staff %}
        <div class="col-sm-4">
          <!-- Widget -->
          <div class="widget">
            <div class="widget-content padding-30 bg-purple-600">
              <div class="widget-watermark darker font-size-60 margin-15"><i class="icon wb-users" aria-hidden="true"></i></div>
              <div class="counter counter-md counter-inverse text-left">
                <div class="counter-number-group">
                  <span class="counter-number">{{ total_users }}</span>
                  <span class="counter-number-related text-capitalize">Users</span>
                </div>
                <div class="counter-label text-capitalize">in Chat Portal</div>
              </div>
            </div>
          </div>
          <!-- End Widget -->
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- End Page -->

<!-- Footer -->
{% include "base_footer.html" %}

{% endblock content %}

{% block main_scripts %}
<script src='{% static "assets/js/app.js" %}'></script>
{% endblock main_scripts %}