server/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('webchat.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('webchat.portal.urls', namespace='portal')),
    url(r'^', include('webchat.payments.urls', namespace='payments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

server/webchat/payments/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^card/$', view=views.ChangeCardView.as_view(), name='update_card'),
    url(regex=r'^make-payment/$', view=views.make_payment, name='make_payment'),
    url(regex=r'^make-payment-api/$', view=views.make_payment_api, name='make_payment_api'),
    url(regex=r'^make-quick-payment/$', view=views.AddCardAndPayView.as_view(), name='make_quick_payment'),

    url(regex=r'^coupon/$', view=views.check_coupon_api, name='check_coupon'),
]

server/webchat/portal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^$', view=views.portal, name='home'),
    url(regex=r'^feedback/$', view=views.feedback, name='feedback'),
    url(regex=r'^rooms/$', view=views.rooms, name='rooms'),
    url(regex=r'^statistics/$', view=views.statistics, name='statistics'),
    url(regex=r'^widgets/$', view=views.widgets, name='widgets'),

    url(regex=r'^disable-widget-tip/$', view=views.disable_widget_tip, name='disable_widget_tip'),
]

server/webchat/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

server/webchat/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

import datetime

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from webchat.core.utils import add_months

PLAN_CHOICES = (
    ('0', 'Trial'),
    ('1', 'Standard'),
    ('2', 'Custom'),
)

TRIAL_PERIOD = 30


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    location = models.CharField(max_length=50, null=True, blank=True)
    job = models.CharField(max_length=100, null=True, blank=True)
    about_me = models.TextField(null=True, blank=True)
    avatar = models.ImageField(upload_to='portraits/', null=True, blank=True)

    default_card = models.CharField(max_length=255, blank=True, null=True,
                                    verbose_name='Default Card ID')
    card_last = models.CharField(max_length=255, blank=True, null=True)
    card_type = models.CharField(max_length=255, blank=True, null=True)
    stripe_id = models.CharField(max_length=255, blank=True, null=True)
    card_expiry = models.CharField(blank=True, null=True, max_length=255)
    payment_active = models.BooleanField(default=False)
    payment_issue = models.CharField(max_length=255, blank=True, null=True)

    plan = models.CharField(max_length=1, choices=PLAN_CHOICES, default='0')
    is_trial = models.BooleanField(default=True)
    paid_at = models.DateTimeField(blank=True, null=True)

    show_widget_tip = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def update_trial(self):
        now = timezone.now()
        if not self.is_trial and self.paid_at:
            paid_period_expires_at = self.paid_at + datetime.timedelta(days=TRIAL_PERIOD)
            if paid_period_expires_at < now:
                self.is_trial = True
                self.save()

    def revoke_access(self):
        now = timezone.now()
        expires_at = self.date_joined + datetime.timedelta(days=TRIAL_PERIOD)
        if expires_at < now:
            return True
        else:
            return False

    def days_left(self):
        days_left = (
            self.date_joined + datetime.timedelta(days=TRIAL_PERIOD) - timezone.now()
        ).days
        return days_left

    def next_pay_day(self):
        if self.paid_at:
            next_pay_day = add_months(self.paid_at, 1)
            return next_pay_day

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

server/webchat/payments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.forms.utils import ErrorList
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from .models import UserPayment
from .models import PlanPrice
from .models import Coupon
from webchat.portal.models import Widget
from webchat.users.models import TRIAL_PERIOD
from .forms import CreditCardForm
from webchat.portal.views import generate_token
from webchat.mailers.payment_confirm_notify import PaymentConfirmNotifyMailer

stripe.api_key = settings.STRIPE_API_KEY


def get_price(plan_name):
    return int(PlanPrice.objects.get(slug=plan_name).price)


class ChangeCardView(FormView):
    template_name = 'payments/add_card.html'
    success_url = '/make-payment/'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        return super(ChangeCardView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(ChangeCardView, self).get_context_data(**kwargs)
        context['user'] = user
        context['payment_active'] = user.payment_active
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ChangeCardView, self).dispatch(*args, **kwargs)


@login_required
def make_payment(request):
    """We can use celery and call this function as a delayed task."""
    user = request.user
    data = dict()
    data['user'] = user
    now = timezone.now()
    standard_price = get_price('standard')

    data['standard_price'] = standard_price
    if Coupon.objects.filter(activated_by=user).exists():
        data['has_coupon'] = True
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
            data['standard_price'] = standard_price - discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > now:
                discount = standard_price * Coupon.objects.get(activated_by=user).discount / 100
                data['standard_price'] = standard_price - discount

    if user.paid_at:
        paid_period_expires_at = user.paid_at + datetime.timedelta(days=TRIAL_PERIOD)
        data['paid_period_expires_at'] = paid_period_expires_at
        if paid_period_expires_at < now:
            data['status'] = 200
        else:
            data['status'] = "You still have an existing active plan"
    else:
        if user.payment_active:
            data['status'] = 200
        else:
            data['status'] = 403
            data['invalid_card'] = True

    return render(request, 'payments/make_payment.html', data)


def make_payment_api(request):
    """ todo: move to DRF """
    user = request.user
    amount = get_price('standard')

    if Coupon.objects.filter(activated_by=user).exists():
        coupon = Coupon.objects.get(activated_by=user)
        if not coupon.duration:
            discount = amount * Coupon.objects.get(activated_by=user).discount / 100
            amount -= discount
        else:
            if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount

    if request.method == 'POST':
        user = request.user

        try:
            widget = Widget.objects.get(owner=request.user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=request.user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=request.user)[0]
        try:
            payment = UserPayment.objects.create(
                user=request.user,
                widget=widget,
                amount=amount,
                description="Charge for monthly subscription {}".format(request.user.email)
            )
            charge = stripe.Charge.create(
                amount=int(amount * 100),
                currency="usd",
                customer=user.stripe_id,
                description="Charge for monthly subscription {}".format(request.user.email),
            )
            payment.trx_id = charge.id
            payment.status = '2'
            payment.history = charge
            payment.save()

            user.plan = '1'
            user.payment_active = True
            user.is_trial = False
            user.paid_at = timezone.now()
            user.save()

            domain = Site.objects.get_current().domain
            url = "https://{}/users/{}/".format(domain, request.user.username)

            context = {
                'username': request.user.username,
                'email': request.user.email,
                'cost': int(payment.amount),
                'url': url,
                'transaction_id': payment.trx_id
            }
            PaymentConfirmNotifyMailer(request).send(context)

            return HttpResponse(json.dumps({"status": True}), content_type="application/json")
        except Exception as e:
            return HttpResponse(
                json.dumps({"status": False, "msg": str(e)}),
                content_type="application/json"
            )


def check_coupon_api(request):
    """ todo: move to DRF """
    if request.method == 'POST':
        coupon_number = request.POST.get('coupon_number')
        if coupon_number:
            try:
                coupon = Coupon.objects.get(number=coupon_number, expired=False)
                coupon.activated_by = request.user
                coupon.activated_at = timezone.now()
                coupon.expired = True
                coupon.save()
                return HttpResponse(json.dumps({'success': True}), content_type="application/json")
            except Coupon.DoesNotExist:
                return HttpResponse(json.dumps({'success': False}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({'success': False}), content_type="application/json")
    else:
        return HttpResponseForbidden()


class AddCardAndPayView(FormView):
    template_name = 'payments/add_and_pay.html'
    success_url = '/make-payment/?p=quick'
    form_class = CreditCardForm

    def form_valid(self, form):
        try:
            token = stripe.Token.create(card={
                "number": form.cleaned_data['number'],
                "exp_month": form.cleaned_data["expiration"].month,
                "exp_year": form.cleaned_data["expiration"].year,
                "cvc": form.cleaned_data['cvc'],
                'name': form.cleaned_data['name'],
            },)
        except Exception as e:
            errors = form._errors.setdefault("number", ErrorList())
            errors.append(e.message)
            return self.form_invalid(form)

        customer = stripe.Customer.create(source=token.id,
                                          description="Payment for {}".format(
                                              self.request.user.username), )

        user = self.request.user
        user.stripe_id = customer['id']
        user.default_card = customer['default_source']
        card = customer['sources']['data'][0]
        user.card_type = card['brand']
        user.card_last = card['last4']
        user.card_expiry = '{}/{}'.format(str(card['exp_month']), str(card['exp_year']))
        user.payment_active = True
        user.save()

        amount = get_price('standard')

        if Coupon.objects.filter(activated_by=user).exists():
            coupon = Coupon.objects.get(activated_by=user)
            if not coupon.duration:
                discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                amount -= discount
            else:
                if coupon.activated_at + datetime.timedelta(days=coupon.duration) > timezone.now():
                    discount = amount * Coupon.objects.get(activated_by=user).discount / 100
                    amount -= discount

        try:
            widget = Widget.objects.get(owner=user)
        except Widget.DoesNotExist:
            token = generate_token()
            widget = Widget.objects.create(owner=user, token=token)
        except Widget.MultipleObjectsReturned:
            widget = Widget.objects.filter(owner=user)[0]
        try:

server/webchat/templates/users/user_detail.html
{% extends "base.html" %}

{% block meta_title %}Profile{% endblock meta_title %}

{% load staticfiles %}
{% load humanize %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/profile.css" %}'>
{% endblock main_style %}

{% block body_class %}site-navbar-small page-profile{% endblock body_class %}


{% block content %}

{% include "base_navbar.html" %}

{% include "base_menubar.html" %}

  <!-- Page -->
  <div class="page animsition">
    <div class="page-content container-fluid">
      <div class="row">
        <div class="col-md-3">
          <!-- Page Widget -->
          <div class="widget widget-shadow text-center">
            <div class="widget-header">
              <div class="widget-header-content">
                {% if user %}
                <a class="avatar avatar-lg" href="javascript:void(0)">
                  {% if user.avatar %}
                  <img src='{{ user.avatar.url }}' alt="{{ user.get_full_name|default:user.username }}">
                  {% else %}
                  <img src='{% static "global/portraits/default.jpg" %}' alt="No Avatar">
                  {% endif %}
                </a>
                <h4 class="profile-user">{{ user.get_full_name|default:user.username }}</h4>
                <p class="profile-job">{{ user.job }}</p>
                <p>{{ user.about_me }}</p>
                <p>
                  <i class="icon icon-color wb-map" aria-hidden="true"></i> {{ user.location }}
                </p>
                {% endif %}
              </div>
            </div>
            <div class="widget-footer">
              <div class="row no-space">
                <div class="col-xs-6">
                  <strong class="profile-stat-count">{{ rooms_count }}</strong>
                  <span>Chats</span>
                </div>
                <div class="col-xs-6">
                  <strong class="profile-stat-count">{{ messages_count }}</strong>
                  <span>Messages</span>
                </div>
              </div>
            </div>
          </div>
          <!-- End Page Widget -->
        </div>
        <div class="col-md-9">
          <!-- Panel -->
          <div class="panel">
            <div class="panel-body nav-tabs-animate">
              <ul class="nav nav-tabs nav-tabs-line" data-plugin="nav-tabs" role="tablist">
                <li class="active" role="presentation"><a data-toggle="tab" href="#activities" aria-controls="activities"
                  role="tab">Payment History </a></li>
              </ul>
              <div class="tab-content">
                <div class="tab-pane active animation-slide-left" id="activities" role="tabpanel">

                  <div class="page-invoice-table table-responsive">
                    <table class="table table-hover text-right">
                      <thead>
                        <tr>
                          <th class="text-center">#</th>
                          <th>Description</th>
                          <th class="text-right">Payment date</th>
                          <th class="text-right">Plan</th>
                          <th class="text-right">Total</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for payment in payments %}
                        <tr>
                          <td class="text-center">
                            {{ forloop.counter }}
                          </td>
                          <td class="text-left">
                            Monthly Subscription
                          </td>
                          <td>{{ payment.created_at }}</td>
                          <td>
                            Standard
                          </td>
                          <td>
                            ${{ payment.amount }}
                          </td>
                        </tr>
                       {% endfor %}
                      </tbody>
                    </table>
                  </div>
{#                  <a class="btn btn-block btn-default profile-readMore" href="{% url 'payments:update_card' %}"#}
{#                  role="button">Change your payment information</a>#}
                </div>
              </div>
            </div>
          </div>
          <!-- End Panel -->
        </div>
        <div class="clearfix"></div>
        <div class="col-md-3">
          <!-- Page Widget -->
          <div class="widget widget-shadow text-center">
            <div class="widget-header">
              <div class="widget-header-content">

            <div class="panel-heading">
              <h3 class="panel-title">Active Plan: {{ user.get_plan_display }}</h3>
            </div>
            <div class="panel-body">
              <div class="wizard-pane" id="exampleBillingOne" role="tabpanel">
                {% if paid_period_expires_at %}
                <p>Your subscription is valid until {{ paid_period_expires_at }}</p>
                {% endif %} {% if user.paid_at %}
                <p>Your card will be automatically processed on <b>{{ user.next_pay_day }}</b></p>
                <p>Last payment date: {{ user.paid_at }}</p>
                <p>{{ user.card_type }} xxxx-xxxx-xxxx-{{ user.card_last }}</p>
                {% endif %}
                {% if status == 200 %}
                <p>Active credit card: {{ user.card_type }} xxxx-xxxx-xxxx-{{ user.card_last }}</p>

                <p>Your card will be charged with ${{ standard_price }}</p>
                {% else %}
                <div class="alert alert-alt alert-info alert-dismissible" role="alert">
                  You can <a href="{% url 'payments:update_card' %}">change your payment information</a>
                </div>
                {% endif %}
              </div>
            </div>
              </div>
            </div>
            <div class="widget-footer">
              <div class="row no-space">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-6">
                </div>
              </div>
            </div>
          </div>
          <!-- End Page Widget -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Page -->

<!-- Footer -->
{% include "base_footer.html" %}

{% endblock content %}

server/webchat/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

server/webchat/templates/users/user_list.html
{% extends "base.html" %}

{% block meta_title %}Users{% endblock meta_title %}

{% load staticfiles %}

{% load humanize %}

{% block main_style %}
<link rel="stylesheet" href='{% static "assets/css/users.css" %}'>
{% endblock main_style %}

{% block body_class %}site-navbar-small page-user{% endblock body_class %}


{% block content %}

{% include "base_navbar.html" %}

{% include "base_menubar.html" %}

<!-- Page -->
<div class="page animsition">
  <div class="page-header">
    <h1 class="page-title">Users</h1>
  </div>
  <div class="page-content container-fluid">
    <!-- Panel -->
    <div class="panel">
      <div class="panel-body">
        <div class="nav-tabs-horizontal">
          <div class="dropdown page-user-sortlist">
            Order By: <a class="dropdown-toggle inline-block" data-toggle="dropdown" href="#" aria-expanded="false">Last Active<span class="caret"></span></a>
            <ul class="dropdown-menu animation-scale-up animation-top-right animation-duration-250" role="menu">
              <li class="active" role="presentation"><a href="javascript:void(0)">Last Active</a></li>
              <li role="presentation"><a href="javascript:void(0)">Username</a></li>
              <li role="presentation"><a href="javascript:void(0)">Location</a></li>
              <li role="presentation"><a href="javascript:void(0)">Register Date</a></li>
            </ul>
          </div>
          <ul class="nav nav-tabs nav-tabs-line" data-plugin="nav-tabs" role="tablist">
            <li class="active" role="presentation"><a data-toggle="tab" href="#all_contacts" aria-controls="all_contacts" role="tab">All Contacts</a></li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane animation-fade active" id="all_contacts" role="tabpanel">
              <ul class="list-group">
                {% for user in user_list %}
                <li class="list-group-item">
                  <div class="media">
                    <div class="media-left">
                      <div class="avatar avatar-online">
                        {% if user.avatar %}
                        <img src='{{ user.avatar.url }}' alt="{{ user.get_full_name|default:user.username }}"> {% else %}
                        <img src='{% static "global/portraits/default.jpg" %}' alt="No Avatar"> {% endif %}
                        <i class="avatar avatar-busy"></i>
                      </div>
                    </div>
                    <div class="media-body">
                      <h4 class="media-heading">
                          <a href="{% url 'users:detail' user.username %}">{{ user.username }}</a>
                          <small>{{ user.last_login|naturaltime }}</small>
                      </h4>
                      <p>
                        <i class="icon icon-color wb-map" aria-hidden="true"></i> {{ user.location }}
                      </p>
                    </div>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Panel -->
  </div>
</div>
<!-- End Page -->

<!-- Footer -->
{% include "base_footer.html" %}

{% endblock content %} {% block main_scripts %}
<script src='{% static "global/js/plugins/responsive-tabs.js" %}'></script>
<script src='{% static "global/js/components/tabs.js" %}'></script>
{% endblock main_scripts %}